name: TCCoasters
version: ${project.version}
build: ${project.build.number}
dev-url: ${project.url}
description: Add-on for TrainCarts that adds free-form rollercoaster track
authors: [bergerkiller]
api-version: 1.13
softdepend: [BKCommonLib, Train_Carts, PlotSquared, LightAPI, ViaVersion]

bstats:
    enabled: true
    plugin-id: 18765

main: com.bergerkiller.bukkit.coasters.Preloader
preloader:
    main: com.bergerkiller.bukkit.coasters.TCCoasters
    hastebinServer: https://paste.traincarts.net
    commands: [tcc, tccoasters]
    depend:
        BKCommonLib: https://www.spigotmc.org/resources/bkcommonlib.39590/
        Train_Carts: https://www.spigotmc.org/resources/traincarts.39592/
